# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Simple"
license = "MIT"
licenselink = ""
description = "A simple blog theme for hugo"
homepage = ""
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.10

[author]
  name = "RuBisCO28"
  homepage = "https://github.com/RuBisCO28"

